name: "Release Build"

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: "ubuntu-latest"

    env:
      GOARCH: amd64
      GOOS: linux
      CGO_ENABLED: 0

    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.25.2"
          cache: true

      - name: "Install dependencies"
        run: go mod download

      - name: "Build"
        run: go build -ldflags="-s -w" -o gosible ./cmd/main.go

      - name: "Create Release"
        uses: "softprops/action-gh-release@v2"
        with:
          name: "Release ${{ github.ref_name }}"
          files: gosible
          draft: false
          prerelease: false
